export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";

export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";

export const NEW_REVİEW_REQUEST = "NEW_REVİEW_REQUEST";
export const NEW_REVİEW_SUCCESS = "NEW_REVİEW_SUCCESS";
export const NEW_REVİEW_RESET = "NEW_REVİEW_RESET";
export const NEW_REVİEW_FAIL = "NEW_REVİEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
