export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";

export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const REVIEW_AVAILABILITY_REQUEST = "REVIEW_AVAILABILITY_REQUEST";
export const REVIEW_AVAILABILITY_SUCCESS = "REVIEW_AVAILABILITY_SUCCESS";
export const REVIEW_AVAILABILITY_FAIL = "REVIEW_AVAILABILITY_FAIL";

export const ADMIN_ROOMS_REQUEST = "ADMIN_ROOMS_REQUEST";
export const ADMIN_ROOMS_SUCCESS = "ADMIN_ROOMS_SUCCESS";
export const ADMIN_ROOMS_FAIL = "ADMIN_ROOMS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
